// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3iiFk2yXgJJWLjdpx_jhU0xuFJN4vgbQ',
    appId: '1:428079534919:web:06b56af4b964f1c0407262',
    messagingSenderId: '428079534919',
    projectId: 'ldauth-bc640',
    authDomain: 'ldauth-bc640.firebaseapp.com',
    storageBucket: 'ldauth-bc640.firebasestorage.app',
    measurementId: 'G-ZFFM3C1WWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbLcJKBs_jD3fLaq3-f0TVrDaWGKLCTc',
    appId: '1:428079534919:android:bfd61476a2321509407262',
    messagingSenderId: '428079534919',
    projectId: 'ldauth-bc640',
    storageBucket: 'ldauth-bc640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0pnSc5Of52fP-xCen-gEz9bA1utX8tc',
    appId: '1:428079534919:ios:42e6417c7034c9ab407262',
    messagingSenderId: '428079534919',
    projectId: 'ldauth-bc640',
    storageBucket: 'ldauth-bc640.firebasestorage.app',
    iosClientId: '428079534919-hp5qnb4j8stka1vuhv6m3vmn3gss7tp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ldfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0pnSc5Of52fP-xCen-gEz9bA1utX8tc',
    appId: '1:428079534919:ios:42e6417c7034c9ab407262',
    messagingSenderId: '428079534919',
    projectId: 'ldauth-bc640',
    storageBucket: 'ldauth-bc640.firebasestorage.app',
    iosClientId: '428079534919-hp5qnb4j8stka1vuhv6m3vmn3gss7tp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ldfrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3iiFk2yXgJJWLjdpx_jhU0xuFJN4vgbQ',
    appId: '1:428079534919:web:2c74ce04c659d1f3407262',
    messagingSenderId: '428079534919',
    projectId: 'ldauth-bc640',
    authDomain: 'ldauth-bc640.firebaseapp.com',
    storageBucket: 'ldauth-bc640.firebasestorage.app',
    measurementId: 'G-88TC40H7MD',
  );
}
